- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "kermit"
    - my_file: "install_{{ my_name }}"

    - packages:
      - ckermit

    - systemd_units:
      - { name: "inetd.service", enabled: yes, state: 'started' }

  tasks:

  - name: "{{ my_name }}  - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }}  - install from repos"
    package: 
       name: "{{ packages }}"
       state: latest

  - name: "{{ my_name }} - configure kermit path"
    replace:
      path: /etc/inetd.conf
      regexp: (^.+)#(kermit.*--root:)(/srv/ftp)\s(.*)
      replace: \2{{ retronas_path }}\4
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - enable inetd service"
    command:
      cmd: "update-inetd --enable {{ my_name }}"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - enable startup services"
    service:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
      enabled: "{{ item.enabled }}"
    with_items: "{{ systemd_units }}"

  handlers:

  - name: "{{ my_name }} - Restart service"
    service:
      name: "{{ item.name }}"
      state: restarted
    with_items: "{{ systemd_units }}"

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "kermit"
    module_state: "present"