- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "ntp"
    - my_file: "install_ntp"

    - my_packages:
      - ntp

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Load RetroNAS systems"
    include_vars: retronas_systems.yml

  - name: "{{ my_name }} - Install build tools"
    package:
       name: "{{ my_packages }}"
       state: latest

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "ntp"
    module_state: "present"